version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: product-service-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_product
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:

